export const CHANGE_SIDEBAR = 'CHANGE_SIDEBAR'
export const CHANGE_SEND_BLOCK = 'CHANGE_SEND_BLOCK'
export const EDIT_REPLY_USER = 'EDIT_REPLY_USER'
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION'